import type { AppDatabase } from "../create-db";
import { elderly } from "../schema";
import {
  COMMUNITY_RT01_ID,
  ELD_SOEPARDI_ID,
  ELD_AMINAH_ID,
  ELD_KARTOWIJOYO_ID,
  ELD_SRI_ID,
  ELD_DJOJODIGDO_ID,
} from "./constants";

export async function seedElderly(db: AppDatabase, authUsers: Record<string, any>) {
  await db.insert(elderly).values([
    // 1. Mbah Soepardi — GREEN (Mandiri & Sehat)
    {
      id: ELD_SOEPARDI_ID,
      communityUnitId: COMMUNITY_RT01_ID,
      name: "Mbah Soepardi",
      phone: "081234567891",
      age: 76,
      gender: "male",
      address: "Jl. Kalpataru No. 45",
      rt: "01",
      rw: "10",
      latitude: -7.948,
      longitude: 112.624,
      mobilityStatus: "independent",
      monitoringMode: "active",
      currentStatus: "green",
      verificationStatus: "verified",
      riskScore: 25,
      medicalHistory: "Hipertensi Derajat 2, Riwayat Stroke Ringan 2024",
      preferredCheckinTime: "07:00",
      notes: "Tinggal sendiri, rumah pagar hijau depan musholla Al-Ikhlas.",
      createdBy: authUsers["kader@gmail.com"]?.id,
    },
    // 2. Mbah Siti Aminah — YELLOW (Pusing / Butuh Bantuan)
    {
      id: ELD_AMINAH_ID,
      communityUnitId: COMMUNITY_RT01_ID,
      name: "Mbah Siti Aminah",
      phone: "081288990011",
      age: 71,
      gender: "female",
      address: "Jl. Melati No. 12",
      rt: "01",
      rw: "10",
      latitude: -7.9488,
      longitude: 112.6245,
      mobilityStatus: "needs_assistance",
      monitoringMode: "active",
      currentStatus: "yellow",
      verificationStatus: "verified",
      riskScore: 55,
      medicalHistory: "Diabetes Melitus Tipe 2, Kolesterol",
      preferredCheckinTime: "07:00",
      notes: "Ibu tinggal sendiri, anak kandung bekerja di Jakarta (Rian).",
      createdBy: authUsers["kader@gmail.com"]?.id,
    },
    // 3. Mbah Kartowijoyo — RED (Darurat / Tirah Baring)
    {
      id: ELD_KARTOWIJOYO_ID,
      communityUnitId: COMMUNITY_RT01_ID,
      name: "Mbah Kartowijoyo",
      phone: null,
      age: 82,
      gender: "male",
      address: "Jl. Kalpataru Gg. 2 No. 8",
      rt: "01",
      rw: "10",
      latitude: -7.9495,
      longitude: 112.6238,
      mobilityStatus: "homebound",
      monitoringMode: "passive",
      currentStatus: "red",
      verificationStatus: "verified",
      riskScore: 85,
      medicalHistory: "Pasca Stroke Berat, Tirah Baring, Penyakit Jantung Koroner",
      preferredCheckinTime: "06:30",
      notes: "Tirah baring (bedridden), tidak memegang HP, pemantauan via kunjungan relawan & keluarga.",
      createdBy: authUsers["kader@gmail.com"]?.id,
    },
    // 4. Mbah Sri Wahyuni — GREY (Belum Merespons Pagi Ini)
    {
      id: ELD_SRI_ID,
      communityUnitId: COMMUNITY_RT01_ID,
      name: "Mbah Sri Wahyuni",
      phone: "081399887711",
      age: 68,
      gender: "female",
      address: "Jl. Mawar No. 5",
      rt: "01",
      rw: "10",
      latitude: -7.9478,
      longitude: 112.6248,
      mobilityStatus: "independent",
      monitoringMode: "active",
      currentStatus: "grey",
      verificationStatus: "verified",
      riskScore: 30,
      medicalHistory: "Kolesterol Tinggi, Maag Kronis",
      preferredCheckinTime: "07:00",
      notes: "Biasanya bangun jam 06.00, hari ini belum ada respon sapaan WhatsApp.",
      createdBy: authUsers["kader@gmail.com"]?.id,
    },
    // 5. Mbah Djojodigdo — PENDING_VERIFICATION (Daftar Mandiri Keluarga)
    {
      id: ELD_DJOJODIGDO_ID,
      communityUnitId: COMMUNITY_RT01_ID,
      name: "Mbah Djojodigdo",
      phone: "081566778899",
      age: 74,
      gender: "male",
      address: "Jl. Kalpataru No. 60",
      rt: "01",
      rw: "10",
      latitude: -7.9491,
      longitude: 112.6255,
      mobilityStatus: "independent",
      monitoringMode: "active",
      currentStatus: "green",
      verificationStatus: "pending_verification",
      riskScore: 0,
      medicalHistory: "Asam Urat",
      preferredCheckinTime: "07:00",
      notes: "Baru didaftarkan oleh anak kemarin malam, menunggu approval Bu RT.",
      createdBy: authUsers["keluarga@gmail.com"]?.id,
    },
  ]);
}
